import React from 'react';
import { useTexture } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';
import * as THREE from 'three';
import { controlState } from '../../../state/controlState';

/**
 * The painting as the sky.
 *
 * An equirectangular pano (generated by Marble from the painting itself) on
 * the inside of a sphere that FOLLOWS THE PLAYER. Following is what puts it at
 * optical infinity: the dome never gets closer, so it reads as a horizon
 * rather than as a wall -- the exact failure Tim called on the splat bubble
 * ("feels like just a panorama") cannot happen to something that admits it is
 * one and stays out of reach.
 *
 * fog:false on the material, or the atmosphere would swallow its own sky.
 */
const SkyDome: React.FC<{ url: string }> = ({ url }) => {
  const texture = useTexture(url);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.mapping = THREE.EquirectangularReflectionMapping;
  const ref = useRef<THREE.Mesh>(null);

  useFrame(() => {
    if (ref.current) {
      ref.current.position.set(
        controlState.playerPosition.x,
        0,
        controlState.playerPosition.z
      );
    }
  });

  return (
    <mesh ref={ref} userData={{ cameraTransparent: true }}>
      <sphereGeometry args={[900, 48, 32]} />
      <meshBasicMaterial map={texture} side={THREE.BackSide} fog={false} />
    </mesh>
  );
};

export default SkyDome;
