#!/usr/bin/env python3
"""
Fetch and self-host the site's faces.

Three of them, and every one was CHECKED rather than trusted. The design system
originally proposed Pixelify Sans for display on the strength of Google listing
a Cyrillic subset for it. It has one -- and that subset is missing О and П.
П appears in half his painting titles. It would have shipped as tofu to every
Russian reader and looked perfect to everyone who could not read it.

So the rule this file exists to enforce: a subset declaration is not coverage.
Open the font, read the cmap, check the alphabet. tools/check-fonts.py does it,
and it runs against what is actually on disk.

  Handjet        display. A multi-script variable pixel face, 1339 glyphs.
  Onest          content and UI. Russian-designed, so Cyrillic is not an export.
  JetBrains Mono data and labels.

Two formats per family, and that is not redundancy:
  .woff2 subsets  for the DOM, split by unicode-range so a reader downloads
                  only the alphabet they are reading.
  .woff whole     for troika, which parses ttf/otf/woff and NOT woff2. The 3D
                  scene cannot use the subsets.

Run:  python3 tools/fetch-fonts.py
"""

import urllib.request, re, os

MODERN = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
          "(KHTML, like Gecko) Chrome/131.0 Safari/537.36")
# An old UA is what makes Google serve woff instead of woff2.
LEGACY = ("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 "
          "(KHTML, like Gecko) Chrome/23 Safari/537.36")

FAMILIES = {
    "Handjet":       ("Handjet:wght@300..700", "Handjet"),
    "Onest":         ("Onest:wght@300..800", "Onest"),
    "JetBrainsMono": ("JetBrains+Mono:wght@400..700", "JetBrains Mono"),
}
# Greek and Vietnamese are bytes nobody reading this site will ever need.
KEEP = {"latin", "latin-ext", "cyrillic", "cyrillic-ext"}


def fetch(url: str, ua: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": ua})
    return urllib.request.urlopen(request, timeout=30).read()


def main() -> None:
    os.makedirs("public/fonts", exist_ok=True)
    out = ["/* Self-hosted. Generated by tools/fetch-fonts.py -- do not edit by hand. */"]

    for slug, (spec, family) in FAMILIES.items():
        css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap", MODERN).decode()
        for block in css.split("/*"):
            match = re.match(r"\s*([\w-]+)\s*\*/", block)
            if not match or match.group(1) not in KEEP:
                continue
            subset = match.group(1)
            url = re.findall(r"url\((https://[^)]+?\.woff2)\)", block)
            if not url:
                continue
            ranges = re.findall(r"unicode-range:\s*([^;]+);", block)
            weights = re.findall(r"font-weight:\s*([^;]+);", block)
            name = f"{slug}-{subset}.woff2"
            open(f"public/fonts/{name}", "wb").write(fetch(url[0], MODERN))
            out.append(
                f"@font-face {{\n"
                f"  font-family: '{family}';\n"
                f"  font-style: normal;\n"
                f"  font-weight: {weights[0] if weights else '400'};\n"
                f"  font-display: swap;\n"
                f"  src: url('/fonts/{name}') format('woff2');\n"
                f"  unicode-range: {ranges[0] if ranges else 'U+0000-FFFF'};\n"
                f"}}"
            )
            print(f"  {name}")

        legacy = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap", LEGACY).decode()
        woff = re.findall(r"url\((https://[^)]+?\.woff)\)", legacy)
        if woff:
            open(f"public/fonts/{slug}.woff", "wb").write(fetch(woff[0], LEGACY))
            print(f"  {slug}.woff (troika)")

    open("src/fonts.css", "w").write("\n\n".join(out) + "\n")
    print("wrote src/fonts.css")


if __name__ == "__main__":
    main()
